### ISSUE TITLE
Search engine optimization

### ISSUE THREAD

**Issue by fwilson-603** [uoft-lgcu/uoft-lgcu.github.io#13]

**Comment by gadanidis** [comment]
It looks like we're actually already pretty high on search engine results for "linguistics graduate course union" (under our old github.io URL, but it redirects to lgcu.ca so that's no problem). Ulife actually shows up first, so if we can eventually figure out how to get that updated that will probably help too.

**Comment by fwilson-603** [comment]
The Ulife account has authorized members who can update it, in theory these are members of the executive. I updated it to Lex, Jessica and possibly Heather when my presidency ended, and from the looks of things it hasn't been updated since. So either of them should be able to either update it themselves, or add you as an authorized member and you can do it. I think it just requires that they sign in to Ulife with their UtorID.

**Comment by fwilson-603** [comment]
I just looked in my notes from 2019, and Jessica was apparently who I put down as the "primary" contact (Lex is "secondary"), so she should definitely be able to edit/add people even if Lex can't.

**Comment by fwilson-603** [comment]
Top search results for "linguistics graduate course union", "u of t lgcu", and "toronto lgcu" all either lead to this website or the ulife page (which now has the correct linke). Closing issue.
